services:
  hapi-fhir-server:
    build: .
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"