spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/fhir
    password: admin
bio:
  elasticsearch:
    host: host.docker.internal
  auth:
    server-url: http://host.docker.internal:8081/
    authorization:
      client-secret: localstacksecret
